#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
#

name: opi-zero-plus

on:
  push:
    branches: 
      - master
  #     ↑↑↑ 改成你的分支名, 一般是master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
        #      ↑↑↑ 改成你的分支名, 一般是master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Sync lastest files
        run: |
          git config --global user.email "leaplu@163.com"
          git config --global user.name "leaplu"
          git remote add openwrt https://github.com/coolsnowwolf/lede.git
          git pull openwrt master --allow-unrelated-histories
          git remote -v
      - name: install aliddns
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/honwen/luci-app-aliddns.git

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          CONFIG_TARGET_sunxi=y
          CONFIG_TARGET_sunxi_cortexa53=y
          CONFIG_TARGET_sunxi_cortexa53_DEVICE_xunlong_orangepi-zero-plus=y
          CONFIG_SUNXI_SD_BOOT_PARTSIZE=20
          CONFIG_TARGET_ROOTFS_PARTSIZE=1900
          CONFIG_ARIA2_BITTORRENT=y
          CONFIG_ARIA2_NOXML=y
          CONFIG_ARIA2_OPENSSL=y
          CONFIG_ARIA2_WEBSOCKET=y
          CONFIG_DOCKER_KERNEL_OPTIONS=y
          CONFIG_DOCKER_NET_MACVLAN=y
          CONFIG_DOCKER_RES_SHAPE=y
          CONFIG_DOCKER_STO_EXT4=y
          CONFIG_GNUTLS_ALPN=y
          CONFIG_GNUTLS_ANON=y
          CONFIG_GNUTLS_DTLS_SRTP=y
          CONFIG_GNUTLS_HEARTBEAT=y
          CONFIG_GNUTLS_OCSP=y
          CONFIG_GNUTLS_PSK=y
          CONFIG_KERNEL_ARM_PMU=y
          CONFIG_KERNEL_BLK_DEV_THROTTLING=y
          CONFIG_KERNEL_CFQ_GROUP_IOSCHED=y
          CONFIG_KERNEL_CFS_BANDWIDTH=y
          CONFIG_KERNEL_CGROUP_PERF=y
          CONFIG_KERNEL_EXT4_FS_POSIX_ACL=y
          CONFIG_KERNEL_FS_POSIX_ACL=y
          CONFIG_KERNEL_IPC_NS=y
          CONFIG_KERNEL_KEYS=y
          CONFIG_KERNEL_MEMCG_SWAP=y
          CONFIG_KERNEL_MEMCG_SWAP_ENABLED=y
          CONFIG_KERNEL_NAMESPACES=y
          CONFIG_KERNEL_NET_NS=y
          CONFIG_KERNEL_PERF_EVENTS=y
          CONFIG_KERNEL_PID_NS=y
          CONFIG_KERNEL_USER_NS=y
          CONFIG_KERNEL_UTS_NS=y
          CONFIG_LIBCURL_COOKIES=y
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          CONFIG_LIBCURL_HTTP=y
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          CONFIG_LIBCURL_PROXY=y
          CONFIG_LIBSODIUM_MINIMAL=y
          CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
          CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
          CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
          CONFIG_OPENVPN_openssl_ENABLE_LZO=y
          CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
          CONFIG_OPENVPN_openssl_ENABLE_PF=y
          CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
          CONFIG_OPENVPN_openssl_ENABLE_SERVER=y
          CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_MAC80211_DEBUGFS=y
          CONFIG_PACKAGE_MAC80211_MESH=y
          CONFIG_PACKAGE_UnblockNeteaseMusic=y
          CONFIG_PACKAGE_amule=y
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_ariang=y
          CONFIG_PACKAGE_attr=y
          CONFIG_PACKAGE_avahi-dbus-daemon=y
          CONFIG_PACKAGE_baidupcs-web=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-chrono=y
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-random=y
          CONFIG_PACKAGE_boost-system=y
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_cgroupfs-mount=y
          CONFIG_PACKAGE_containerd=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_dbus=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_docker-ce=y
          CONFIG_PACKAGE_fdisk=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_hd-idle=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_icu=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-extra=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_iw=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kmod-br-netfilter=y
          CONFIG_PACKAGE_kmod-cfg80211=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-dax=y
          CONFIG_PACKAGE_kmod-dm=y
          CONFIG_PACKAGE_kmod-dummy=y
          CONFIG_PACKAGE_kmod-gre=y
          CONFIG_PACKAGE_kmod-ikconfig=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-mac80211=y
          CONFIG_PACKAGE_kmod-macvlan=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-nf-ipvs=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-ehci=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-printer=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-veth=y
          CONFIG_PACKAGE_krb5-libs=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libavahi-client=y
          CONFIG_PACKAGE_libavahi-dbus-support=y
          CONFIG_PACKAGE_libbfd=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libdaemon=y
          CONFIG_PACKAGE_libdb47=y
          CONFIG_PACKAGE_libdbus=y
          CONFIG_PACKAGE_libdevmapper=y
          CONFIG_PACKAGE_libdouble-conversion=y
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libevent2=y
          CONFIG_PACKAGE_libexif=y
          CONFIG_PACKAGE_libexpat=y
          CONFIG_PACKAGE_libfdisk=y
          CONFIG_PACKAGE_libffi=y
          CONFIG_PACKAGE_libffmpeg-audio-dec=y
          CONFIG_PACKAGE_libflac=y
          CONFIG_PACKAGE_libgd=y
          CONFIG_PACKAGE_libgdbm=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_libhttp-parser=y
          CONFIG_PACKAGE_libid3tag=y
          CONFIG_PACKAGE_libjpeg=y
          CONFIG_PACKAGE_liblzo=y
          CONFIG_PACKAGE_libmbedtls=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnetwork=y
          CONFIG_PACKAGE_libnghttp2=y
          CONFIG_PACKAGE_libogg=y
          CONFIG_PACKAGE_libpcre2-16=y
          CONFIG_PACKAGE_libpng=y
          CONFIG_PACKAGE_libpopt=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_libsqlite3=y
          CONFIG_PACKAGE_libtasn1=y
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_libupnp=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libvorbis=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libwrap=y
          CONFIG_PACKAGE_libwxbase=y
          CONFIG_PACKAGE_libxml2=y
          CONFIG_PACKAGE_libzstd=y
          CONFIG_PACKAGE_luci-app-aliddns=y
          CONFIG_PACKAGE_luci-app-amule=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          CONFIG_PACKAGE_luci-app-dnspod=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-minidlna=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          CONFIG_PACKAGE_luci-app-openvpn-server=y
          CONFIG_PACKAGE_luci-app-pptp-server=y
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-samba4=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ssrserver-python=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-transmission=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-unblockneteasemusic-mini=y
          CONFIG_PACKAGE_luci-app-usb-printer=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-vnstat=y
          CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-xlnetacc=y
          CONFIG_PACKAGE_luci-i18n-amule-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-minidlna-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-openvpn-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-pptp-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qbittorrent-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ssrserver-python-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-transmission-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-usb-printer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-v2ray-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vnstat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-lib-docker=y
          CONFIG_PACKAGE_luci-lib-json=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          # CONFIG_PACKAGE_luci-proto-relay is not set
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_minidlna=y
          CONFIG_PACKAGE_mount-utils=y
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_node=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_openvpn-easy-rsa=y
          CONFIG_PACKAGE_openvpn-openssl=y
          CONFIG_PACKAGE_p910nd=y
          CONFIG_PACKAGE_pptpd=y
          CONFIG_PACKAGE_python=y
          CONFIG_PACKAGE_python-base=y
          CONFIG_PACKAGE_python-codecs=y
          CONFIG_PACKAGE_python-compiler=y
          CONFIG_PACKAGE_python-ctypes=y
          CONFIG_PACKAGE_python-db=y
          CONFIG_PACKAGE_python-decimal=y
          CONFIG_PACKAGE_python-distutils=y
          CONFIG_PACKAGE_python-email=y
          CONFIG_PACKAGE_python-gdbm=y
          CONFIG_PACKAGE_python-light=y
          CONFIG_PACKAGE_python-logging=y
          CONFIG_PACKAGE_python-multiprocessing=y
          CONFIG_PACKAGE_python-ncurses=y
          CONFIG_PACKAGE_python-openssl=y
          CONFIG_PACKAGE_python-pydoc=y
          CONFIG_PACKAGE_python-sqlite3=y
          CONFIG_PACKAGE_python-unittest=y
          CONFIG_PACKAGE_python-xml=y
          CONFIG_PACKAGE_qBittorrent=y
          CONFIG_PACKAGE_qt5-core=y
          CONFIG_PACKAGE_qt5-network=y
          CONFIG_PACKAGE_qt5-xml=y
          CONFIG_PACKAGE_rblibtorrent=y
          # CONFIG_PACKAGE_relayd is not set
          CONFIG_PACKAGE_runc=y
          CONFIG_PACKAGE_samba4-libs=y
          CONFIG_PACKAGE_samba4-server=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-server=y
          CONFIG_PACKAGE_simple-obfs=y
          CONFIG_PACKAGE_srelay=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_tini=y
          CONFIG_PACKAGE_transmission-daemon-openssl=y
          CONFIG_PACKAGE_transmission-web-control=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_v2ray=y
          CONFIG_PACKAGE_v2ray-plugin=y
          CONFIG_PACKAGE_vnstat=y
          CONFIG_PACKAGE_vnstati=y
          CONFIG_PACKAGE_watchcat=y
          CONFIG_PACKAGE_wireless-regdb=y
          CONFIG_PACKAGE_wpad-mini=y
          CONFIG_PACKAGE_wsdd2=y
          CONFIG_SAMBA4_SERVER_AVAHI=y
          CONFIG_SAMBA4_SERVER_VFS=y
          CONFIG_SQLITE_FTS3=y
          CONFIG_SQLITE_RTREE=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1900
          CONFIG_V2RAY_DISABLE_NONE=y
          CONFIG_V2RAY_EXCLUDE_ASSETS=y
          CONFIG_V2RAY_EXCLUDE_V2CTL=y
          CONFIG_V2RAY_JSON_INTERNAL=y
          CONFIG_WPA_MSG_MIN_PRIORITY=3
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          # CONFIG_SAMBA4_SERVER_NETBIOS is not set
          # CONFIG_V2RAY_COMPRESS_UPX is not set
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: bin/targets
